# Basic Information 
title: Zhiyuan Cheng
position: Ph.D. Candidate in Computer Science
affiliation: Purdue University
affiliation_link: https://cs.purdue.edu/
nav_logo: ./assets/img/PU-H.svg
nav_link: https://cs.purdue.edu/
email: cheng443 (at) purdue (dot) edu
# email2: yliu538 (at) jhu.edu

# Search Engine Optimization (SEO)
keywords: zhiyuan cheng, cheng zhiyuan, zhiyuan cheng purdue, zhiyuan purdue
canonical: https://bob-cheng.github.io/
description: Zhiyuan Cheng is a PhD candidate at Purdue University. His research interest lies in AI security, machine learning and computer vision.

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: false

# The option is used to show the last update time.
enable_last_update: true

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?user=dVchB-gAAAAJ
# cv_link: https://pages.jh.edu/yliu538/files/Yaoyao_Liu_Curriculum_Vitae.pdf
github_link: https://github.com/bob-cheng/
linkedin: https://www.linkedin.com/in/bobchengzy/
# twitter: https://twitter.com/YaoyaoLiu1/

# Images 
avatar: ./assets/img/avatar.jpg
favicon: ./assets/img/favicon-user.png
favicon_dark: ./assets/img/favicon-user.png

# Footnotes
footnote: # Feel free to use my website's source code.
footnote_link: # https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
clustrmaps_id: 1jxGdyO9mQ6iHzvC_n3lbwmTV3-9qtkf0vjxGwvTf-o
google_analytics: G-9VC44PZMKM

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
